// Generated by npm run catalog:generate. Do not edit by hand.
import type { Theme } from "@/lib/themes";

export const GENERATED_THEMES = [
  {
    "slug": "desert-signal",
    "name": "Desert Signal",
    "summary": "沙丘金、陶土橙与绿洲青组成的暖色主题，适合规划路线和持续推进长任务。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "orange",
      "teal",
      "neutral"
    ],
    "tags": [
      "原创",
      "沙丘",
      "暖色",
      "绿洲",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-18T04:06:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "desert-signal",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-desert-signal-v1.0.0/Codex-Skin-theme-desert-signal-1.0.0.dreamskin",
      "sha256": "b04700a19de8333b93b9466bc98b5cf33074957e801cff33f3e65c54280f1a87",
      "size": 273794
    },
    "previewImage": "/theme-previews/desert-signal.png",
    "previewStyle": {
      "backgroundColor": "#f3dfbd",
      "backgroundImage": "linear-gradient(145deg, #f3dfbd, #ead0a4)",
      "panelColor": "#f3dfbd",
      "panelBorder": "#d5b786",
      "textColor": "#3d3028",
      "mutedTextColor": "#806d5e",
      "accentColor": "#d86f3d",
      "accentSoft": "#ead0a4",
      "codeColor": "#147f78",
      "shadow": "0 28px 80px rgba(43,54,67,.18)",
      "pattern": "horizon"
    }
  },
  {
    "slug": "dilraba-star",
    "name": "Dilraba Star",
    "summary": "星光蓝紫与甜酷舞台氛围，包含真实背景、Logo、首页引导与四张快捷操作卡。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "gradient",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "violet",
      "blue"
    ],
    "tags": [
      "真实主题",
      "星光",
      "人物",
      "甜酷",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": true,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T06:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "dilraba-star",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v1/Codex-Skin-theme-dilraba-star-1.0.0.dreamskin",
      "sha256": "45eed254d3ecbc13e2c13cb0efbde3678594ec290683d6db641893aca61ffe17",
      "size": 1015797
    },
    "previewImage": "/theme-previews/dilraba-star.png",
    "previewStyle": {
      "backgroundColor": "#f4f1ff",
      "backgroundImage": "linear-gradient(#f4f1ff, #ece6ff)",
      "panelColor": "#f4f1ff",
      "panelBorder": "#c7b8ef",
      "textColor": "#151b72",
      "mutedTextColor": "#7476a1",
      "accentColor": "#7b49ff",
      "accentSoft": "#e6dcff",
      "codeColor": "#b459ff",
      "shadow": "0 28px 80px rgba(21,27,114,.22)",
      "pattern": "stars"
    }
  },
  {
    "slug": "enfp-pop",
    "name": "ENFP Pop",
    "summary": "高饱和青橙与自由脑暴氛围，面向快速原型、灵感探索和轻快创作。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "editorial",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "teal",
      "orange"
    ],
    "tags": [
      "真实主题",
      "ENFP",
      "脑暴",
      "高饱和",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T06:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "enfp-pop",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v1/Codex-Skin-theme-enfp-pop-1.0.0.dreamskin",
      "sha256": "b9f9b08b2707a83c4b404c4dc98d82334baa0b01e5c3c44fda3554d7438da336",
      "size": 956764
    },
    "previewImage": "/theme-previews/enfp-pop.png",
    "previewStyle": {
      "backgroundColor": "#fffaf0",
      "backgroundImage": "linear-gradient(#fffaf0, #fff0dc)",
      "panelColor": "#fffaf0",
      "panelBorder": "#efcfae",
      "textColor": "#202335",
      "mutedTextColor": "#77726d",
      "accentColor": "#12bfa5",
      "accentSoft": "#d7f5ef",
      "codeColor": "#ffb31a",
      "shadow": "0 28px 80px rgba(255,106,87,.2)",
      "pattern": "paper"
    }
  },
  {
    "slug": "glacier-glass",
    "name": "Glacier Glass",
    "summary": "冰川蓝、玻璃白与极光青构成的清透主题，适合审查、整理与高密度信息阅读。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "gradient",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "blue",
      "teal",
      "neutral"
    ],
    "tags": [
      "原创",
      "冰川",
      "玻璃",
      "清透",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-18T04:08:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "glacier-glass",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-glacier-glass-v1.0.0/Codex-Skin-theme-glacier-glass-1.0.0.dreamskin",
      "sha256": "2efa9581698e40cd57e97663afab2b7e32999632975d893d04fc2bf73c6c85bc",
      "size": 338761
    },
    "previewImage": "/theme-previews/glacier-glass.png",
    "previewStyle": {
      "backgroundColor": "#eaf7fa",
      "backgroundImage": "linear-gradient(145deg, #eaf7fa, #ccebf2)",
      "panelColor": "#eaf7fa",
      "panelBorder": "#acd3dc",
      "textColor": "#173746",
      "mutedTextColor": "#66818d",
      "accentColor": "#168fb2",
      "accentSoft": "#ccebf2",
      "codeColor": "#5c69d8",
      "shadow": "0 28px 80px rgba(43,54,67,.18)",
      "pattern": "aurora"
    }
  },
  {
    "slug": "ivory-alley",
    "name": "Pupu Ivory Alley",
    "summary": "噗噗与暖象牙白、雾蓝巷景组成的明亮人物主题，为日间编码保留轻盈、清晰的视觉空间。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "editorial",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "neutral",
      "blue",
      "rose"
    ],
    "tags": [
      "人物",
      "噗噗",
      "浅色",
      "城市",
      "学院风",
      "留白"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.1.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-21T08:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "creator-submitted-assets"
    },
    "package": null,
    "previewImage": "/theme-previews/ivory-alley.png",
    "previewStyle": {
      "backgroundColor": "#F8F4EE",
      "backgroundImage": "linear-gradient(145deg, #F8F4EE, #CBD2DC)",
      "panelColor": "#F8F4EE",
      "panelBorder": "#D8CEC5",
      "textColor": "#2C3342",
      "mutedTextColor": "#7A7372",
      "accentColor": "#A5445C",
      "accentSoft": "#EED9DC",
      "codeColor": "#64748B",
      "shadow": "0 28px 80px rgba(44,51,66,.16)",
      "pattern": "paper"
    }
  },
  {
    "slug": "jackson-sage",
    "name": "Jackson Sage",
    "summary": "鼠尾草绿与安静留白氛围，完整呈现真实首页背景、品牌元素和引导文案。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "green",
      "neutral"
    ],
    "tags": [
      "真实主题",
      "人物",
      "鼠尾草",
      "留白",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": true,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T06:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "jackson-sage",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v1/Codex-Skin-theme-jackson-sage-1.0.0.dreamskin",
      "sha256": "d737eb406bcb8612c6ff4814a2e9644287617dcc23d78fa99b2f698cb02c4abd",
      "size": 1233340
    },
    "previewImage": "/theme-previews/jackson-sage.png",
    "previewStyle": {
      "backgroundColor": "#f6f4ea",
      "backgroundImage": "linear-gradient(#f6f4ea, #e8eddd)",
      "panelColor": "#f6f4ea",
      "panelBorder": "#bdc8aa",
      "textColor": "#3d4a31",
      "mutedTextColor": "#777d70",
      "accentColor": "#879966",
      "accentSoft": "#e3e9d8",
      "codeColor": "#b99b68",
      "shadow": "0 28px 80px rgba(61,74,49,.2)",
      "pattern": "mist"
    }
  },
  {
    "slug": "kun-stage",
    "name": "KUN Stage",
    "summary": "黑金舞台与聚光灯氛围，使用真实主题背景、Logo 和完整首页引导内容。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "dark",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "black",
      "orange"
    ],
    "tags": [
      "真实主题",
      "人物",
      "黑金",
      "舞台",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T06:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "kun-stage",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v1/Codex-Skin-theme-kun-stage-1.0.0.dreamskin",
      "sha256": "5b6be40451f7b9d69daca1c36d85b5f1115054ddf3cac61c27606f500cad5d7e",
      "size": 1115718
    },
    "previewImage": "/theme-previews/kun-stage.png",
    "previewStyle": {
      "backgroundColor": "#101211",
      "backgroundImage": "linear-gradient(#101211, #050606)",
      "panelColor": "#101211",
      "panelBorder": "#4b4436",
      "textColor": "#ead8b5",
      "mutedTextColor": "#9b927f",
      "accentColor": "#d5b47c",
      "accentSoft": "#352f25",
      "codeColor": "#d5b47c",
      "shadow": "0 28px 80px rgba(0,0,0,.55)",
      "pattern": "embers"
    }
  },
  {
    "slug": "lunar-terminal",
    "name": "Lunar Terminal",
    "summary": "月面银、深空蓝与冷光网格塑造的工程终端，专为调试、构建与发布节奏设计。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "dark",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "blue",
      "neutral",
      "black"
    ],
    "tags": [
      "原创",
      "月面",
      "终端",
      "工程感",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": true,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-18T04:03:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "lunar-terminal",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-lunar-terminal-v1.0.0/Codex-Skin-theme-lunar-terminal-1.0.0.dreamskin",
      "sha256": "1164089b1f17ce929a5c3431aac63b7caca0c99ceda2c65600d43af3565d8b1a",
      "size": 263434
    },
    "previewImage": "/theme-previews/lunar-terminal.png",
    "previewStyle": {
      "backgroundColor": "#0b1424",
      "backgroundImage": "linear-gradient(145deg, #0b1424, #182b45)",
      "panelColor": "#0b1424",
      "panelBorder": "#29466d",
      "textColor": "#eef6ff",
      "mutedTextColor": "#8fa1b8",
      "accentColor": "#7db9ff",
      "accentSoft": "#182b45",
      "codeColor": "#b7c8e8",
      "shadow": "0 28px 80px rgba(0,0,0,.48)",
      "pattern": "grid"
    }
  },
  {
    "slug": "mono-focus",
    "name": "Mono Focus",
    "summary": "黑白留白中只保留一笔钴蓝，强调层级、键盘效率与无干扰工作。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "minimal",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "neutral",
      "black",
      "blue"
    ],
    "tags": [
      "原创",
      "黑白",
      "极简",
      "专注",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-18T04:05:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "mono-focus",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-mono-focus-v1.0.0/Codex-Skin-theme-mono-focus-1.0.0.dreamskin",
      "sha256": "8e71d5c4ecc4bfc3391ad3615d0b62e90d5a758ced911a1791831b03e7cb2793",
      "size": 221402
    },
    "previewImage": "/theme-previews/mono-focus.png",
    "previewStyle": {
      "backgroundColor": "#f5f4ef",
      "backgroundImage": "linear-gradient(145deg, #f5f4ef, #dfe5ff)",
      "panelColor": "#f5f4ef",
      "panelBorder": "#c9c7c0",
      "textColor": "#151515",
      "mutedTextColor": "#74726c",
      "accentColor": "#2457ff",
      "accentSoft": "#dfe5ff",
      "codeColor": "#2457ff",
      "shadow": "0 28px 80px rgba(43,54,67,.18)",
      "pattern": "grid"
    }
  },
  {
    "slug": "moss-library",
    "name": "Moss Library",
    "summary": "苔绿、旧木与琥珀灯光组成的安静书房，适合长时间阅读代码与梳理知识。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "green",
      "orange",
      "black"
    ],
    "tags": [
      "原创",
      "苔藓",
      "书房",
      "自然",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-18T04:02:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "moss-library",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-moss-library-v1.0.0/Codex-Skin-theme-moss-library-1.0.0.dreamskin",
      "sha256": "ff0cf4e379788f25d073012c454c551ce4a2d2a139e787a56a0cadae841f6b38",
      "size": 424279
    },
    "previewImage": "/theme-previews/moss-library.png",
    "previewStyle": {
      "backgroundColor": "#16231c",
      "backgroundImage": "linear-gradient(145deg, #16231c, #2b4032)",
      "panelColor": "#16231c",
      "panelBorder": "#405546",
      "textColor": "#f0f1df",
      "mutedTextColor": "#9aa995",
      "accentColor": "#9fbd76",
      "accentSoft": "#2b4032",
      "codeColor": "#e2b66d",
      "shadow": "0 28px 80px rgba(0,0,0,.48)",
      "pattern": "mist"
    }
  },
  {
    "slug": "neon-tides",
    "name": "Neon Tides",
    "summary": "深海黑与青粉流光交叠的沉浸主题，为夜间编码保留安静、清晰的视觉中心。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "dark",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "teal",
      "rose",
      "black"
    ],
    "tags": [
      "原创",
      "霓虹",
      "深色",
      "沉浸",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": true,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-18T04:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "neon-tides",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-neon-tides-v1.0.0/Codex-Skin-theme-neon-tides-1.0.0.dreamskin",
      "sha256": "94430b0e843b1e71885e254bc86a1dd7184906b3e05ea743f7dd71cd481182d6",
      "size": 4164795
    },
    "previewImage": "/theme-previews/neon-tides.png",
    "previewStyle": {
      "backgroundColor": "#07111f",
      "backgroundImage": "linear-gradient(145deg, #07111f, #123746)",
      "panelColor": "#07111f",
      "panelBorder": "#24576a",
      "textColor": "#eafcff",
      "mutedTextColor": "#8da7b5",
      "accentColor": "#24d6d1",
      "accentSoft": "#123746",
      "codeColor": "#ff4fa3",
      "shadow": "0 28px 80px rgba(0,0,0,.48)",
      "pattern": "aurora"
    }
  },
  {
    "slug": "paper-crane",
    "name": "Paper Crane",
    "summary": "米纸、朱砂与墨色构成的东方编辑风主题，适合写作、阅读与耐心推演。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "editorial",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "neutral",
      "orange"
    ],
    "tags": [
      "原创",
      "纸张",
      "东方",
      "编辑风",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": true,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-18T04:01:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "paper-crane",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-paper-crane-v1.0.0/Codex-Skin-theme-paper-crane-1.0.0.dreamskin",
      "sha256": "7d0efa37ec340973562c324da85b56e8a56ffb95310c2e318059b8fcb2e787af",
      "size": 309457
    },
    "previewImage": "/theme-previews/paper-crane.png",
    "previewStyle": {
      "backgroundColor": "#f4eddc",
      "backgroundImage": "linear-gradient(145deg, #f4eddc, #ead9c3)",
      "panelColor": "#f4eddc",
      "panelBorder": "#cdbda8",
      "textColor": "#2f2923",
      "mutedTextColor": "#776d61",
      "accentColor": "#c94b32",
      "accentSoft": "#ead9c3",
      "codeColor": "#315f68",
      "shadow": "0 28px 80px rgba(43,54,67,.18)",
      "pattern": "paper"
    }
  },
  {
    "slug": "peach-soda",
    "name": "Peach Soda",
    "summary": "蜜桃粉、薄荷绿与奶油白的轻快主题，让原型、脑暴和小步迭代更有活力。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "gradient",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "rose",
      "teal",
      "orange"
    ],
    "tags": [
      "原创",
      "蜜桃",
      "汽水",
      "轻快",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-18T04:04:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "peach-soda",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-peach-soda-v1.0.0/Codex-Skin-theme-peach-soda-1.0.0.dreamskin",
      "sha256": "5444d5abfa2aac1a7a89ad419a40a5122c971e0d256323b3067b410abbcfa8d8",
      "size": 307433
    },
    "previewImage": "/theme-previews/peach-soda.png",
    "previewStyle": {
      "backgroundColor": "#fff4ed",
      "backgroundImage": "linear-gradient(145deg, #fff4ed, #ffd9d0)",
      "panelColor": "#fff4ed",
      "panelBorder": "#f1c3b9",
      "textColor": "#3e3440",
      "mutedTextColor": "#88757c",
      "accentColor": "#f06f7f",
      "accentSoft": "#ffd9d0",
      "codeColor": "#20a995",
      "shadow": "0 28px 80px rgba(43,54,67,.18)",
      "pattern": "orb"
    }
  },
  {
    "slug": "user-upload-test",
    "name": "我的第一个主题",
    "summary": "一个清晰、舒适，适合日常使用的 Codex 主题。",
    "author": {
      "name": "lixiaobai",
      "handle": "lixiaobaivv",
      "curated": false
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "blue"
    ],
    "tags": [
      "社区主题",
      "浅色",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T15:55:14.729Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "creator-submitted-assets"
    },
    "package": {
      "published": true,
      "id": "user-upload-test",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-user-upload-test-v1.0.0/Codex-Skin-theme-user-upload-test-1.0.0.dreamskin",
      "sha256": "1093139230d37e89c07c3a4d490b183aba23c1c58a425e34cf08a954a12555af",
      "size": 4072529
    },
    "previewImage": "/theme-previews/user-upload-test.png",
    "previewStyle": {
      "backgroundColor": "#f7f6f2",
      "backgroundImage": "linear-gradient(145deg, #f7f6f2, #dddbff)",
      "panelColor": "#f7f6f2",
      "panelBorder": "#070709",
      "textColor": "#20212a",
      "mutedTextColor": "#131318",
      "accentColor": "#635bff",
      "accentSoft": "#dddbff",
      "codeColor": "#635bff",
      "shadow": "0 28px 80px #36328c55",
      "pattern": "mist"
    }
  },
  {
    "slug": "user-upload-test2",
    "name": "我的第一个主题2",
    "summary": "一个清晰、舒适，适合日常使用的 Codex 主题。",
    "author": {
      "name": "lixiaobai",
      "handle": "lixiaobaivv",
      "curated": false
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "blue"
    ],
    "tags": [
      "社区主题",
      "浅色",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T16:57:37.806Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "creator-submitted-assets"
    },
    "package": null,
    "previewImage": "/theme-previews/user-upload-test2.png",
    "previewStyle": {
      "backgroundColor": "#f7f6f2",
      "backgroundImage": "linear-gradient(145deg, #f7f6f2, #dddbff)",
      "panelColor": "#f7f6f2",
      "panelBorder": "#070709",
      "textColor": "#20212a",
      "mutedTextColor": "#131318",
      "accentColor": "#635bff",
      "accentSoft": "#dddbff",
      "codeColor": "#635bff",
      "shadow": "0 28px 80px #36328c55",
      "pattern": "mist"
    }
  },
  {
    "slug": "violet-rain",
    "name": "Violet Rain",
    "summary": "深紫雨幕与蓝色路灯交织的夜行主题，为排错和深夜创作提供低亮专注感。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "dark",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "violet",
      "blue",
      "black"
    ],
    "tags": [
      "原创",
      "紫雨",
      "夜行",
      "低亮",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-18T04:07:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "violet-rain",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/theme-violet-rain-v1.0.0/Codex-Skin-theme-violet-rain-1.0.0.dreamskin",
      "sha256": "d8fc89fe56645152e49b7e211d7af96d4fb369d4e9bef3a90a95ce0b3a131847",
      "size": 672542
    },
    "previewImage": "/theme-previews/violet-rain.png",
    "previewStyle": {
      "backgroundColor": "#151126",
      "backgroundImage": "linear-gradient(145deg, #151126, #2d2449)",
      "panelColor": "#151126",
      "panelBorder": "#433766",
      "textColor": "#f0ecff",
      "mutedTextColor": "#9c94b5",
      "accentColor": "#a98bff",
      "accentSoft": "#2d2449",
      "codeColor": "#67c4ff",
      "shadow": "0 28px 80px rgba(0,0,0,.48)",
      "pattern": "stars"
    }
  },
  {
    "slug": "zhu-xudan-racing",
    "name": "Zhu Xudan Racing",
    "summary": "赛车红黑与卡丁车疾速氛围，包含人物背景、竞速 Logo、首页引导与四张快捷操作卡。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "dark",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "rose",
      "orange",
      "black"
    ],
    "tags": [
      "祝绪丹",
      "人物",
      "赛车",
      "卡丁车",
      "深色",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T08:11:01.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "zhu-xudan-racing",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v2/Codex-Skin-theme-zhu-xudan-racing-1.0.0.dreamskin",
      "sha256": "9da9d441fe42723f536d2edc30fb87b35ec93cbbc8f4e13d148ec4898e245ac0",
      "size": 3083241
    },
    "previewImage": "/theme-previews/zhu-xudan-racing.png",
    "previewStyle": {
      "backgroundColor": "#17191e",
      "backgroundImage": "linear-gradient(135deg, #0d0f12, #2a1718)",
      "panelColor": "#17191e",
      "panelBorder": "#4a2a2b",
      "textColor": "#f7f4ef",
      "mutedTextColor": "#b9b3ad",
      "accentColor": "#e53935",
      "accentSoft": "#4a1f20",
      "codeColor": "#ffb020",
      "shadow": "0 28px 80px rgba(0,0,0,.42)",
      "pattern": "embers"
    }
  }
] as const satisfies readonly Theme[];
